ARG TF_IMAGE=tensorflow/tensorflow:${TF_VERSION}-gpu

FROM ${TF_IMAGE}

WORKDIR /workspace
USER root

COPY apt-packages.txt .
RUN apt-get update && \
    xargs -a apt-packages.txt apt-get install -y && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src /workspace/src

WORKDIR /workspace

CMD ["python", "-m", "{{package_name}}.train"]

